### ISSUE TITLE
Clicking on any H265/HEVC videos crashes to Roku Home Menu

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin-archive/jellyfin-roku-legacy#1155]
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version: 1.6 build 3

## Describe the bug
It started today, i haven't changed any settings and it was all working till a few hours ago. Now when i click on any H265/HEVC videos it just crashes to the Roku Home Menu. I have restarted the Roku and the server but it hasn't fixed it. I can still play H264 files. I do force Audio Transcoding as most of my rips are 5:1 but i have a stereo TV so it would be too quite then way too loud. I changed that setting almost three weeks ago and up till today i was watching my TV Show no problems but now it crashes.

## How To Reproduce

1. Go to Show with H265/HEVC Codec 
2. Click on Episode
4. Crash to Roku home menu occurs

## Expected behavior
 The episode plays with no problems

## Logs
There are no FFmpeg logs for transcoding as it doesnt seem to get that far. My server logs doesnt show any thing out of the ordinary just plugins doing things but Roku App doesnt use Plugins as far as i'm aware

## Connection Information

- Is server local or remote? The Server is local, Roku is local over WIFI
- Is server connection HTTP or HTTPS? HTTP using ip address and port not Domain or DNS Name

## Additional context
I had a similar issue in January but it resolved its self Issue #994

**Comment by 1hitsong** [comment]
These kind of codec specific issues are always so hard to run down because of all the options and nuance that can exist with the video files.. Do you mind if we try a new approach to run this down?

So we can recreate the issue as closely as possible, can you create a HandBrake preset that will convert a video into an H265 video that causes the crash, then export the preset and post it here? That way we can convert a video into the exact same format for debugging.

**Comment by Gaffers2277** [comment]
Yeah i thought that could be the case. I can give it a go tomorrow. Would screenshots of settings help as well?

**Comment by Gaffers2277** [comment]
I'm not sure if the preset is an exact match, I couldn't find all matching settings but the video i transcoded through the preset does cause the same crash.

[H265 Preset Test.zip](https://github.com/jellyfin/jellyfin-roku/files/11132216/H265.Preset.Test.zip)

I have done some more testing add played all the codecs i have.
 All H264 videos play no problem, most are Direct Playing. 
Mpeg4 is transcoded to H264 but i did notice one show that the video lagged and glitched with frames dropping and visually merging making it unwatchable. The rest i tested work. 
VP9 plays audio but no video, though they are downloads from YouTube with googles VP9 codec
Xvid seems to just crash

Finally H265/HEVC - Some work some don't - I tried Stargate Atlantis and it worked then tried Grimm and it crashed. Here are the media info from Jellyfin for those shows.

Stargate Atalantis - 
Video
Title 1080p HEVC SDR
Codec HEVC
Profile Main 10
Level 120
Resolution 1920x1080
Aspect ratio 16:9
Interlaced No
Framerate 23.976025
Bitrate 3277 kbps
Bit depth 10 bit
Video range SDR
Video range type SDR
Colour spacebt 709
Colour transferbt 709
Colour primariesbt 709
Pixel format yuv420p10le
Ref frames1

Audio
Title English - Dolby Digital - 5.1 - Default
Language eng
Codec AC3
Layout 5.1
Channels 6 ch
Bitrate 448 kbps
Sample rate 48000 Hz
Default Yes
Forced No
External No

Grimm - 
Video
Title 1080p HEVC SDR
Codec HEVC
Profile Main 10
Level 120
Resolution 1920x1080
Aspect ratio 16:9
Interlaced No
Framerate 23.976025
Bitrate 13827 kbps
Bit depth 10 bit
Video range SDR
Video range type SDR
Colour space bt709
Colour transfer bt709
Colour primaries bt709
Pixel format yuv420p10le
Ref frames 1

Audio
Title English - DTS-HD MA - 5.1 - Default
Language eng
Codec DTS
Profile DTS-HD MA
Layout 5.1
Channels 6 ch
Bitrate 2462 kbps
Sample rate 48000 Hz
Bit depth 24 bit
Default Yes
Forced No
External No

As far as i can tell the only differences are Video Bitrate and Audio Codec. The thing is Grimm worked fine till yesterday so im confused why it suddenly crashes back to Roku Home Menu. I don't even get the Error During Playback popup, it just crashes.

Here is a screen shot of my playback setting, Right is Server settings (they are probably wrong but i have no idea what the settings do so i left it as default. Left is the Family User playback settings for the Roku Account.


![Screenshot (62)](https://user-images.githubusercontent.com/51297751/229357093-94a2ba32-4b69-41a6-a3d6-c7d1046fb72c.png)

![Screenshot (63)](https://user-images.githubusercontent.com/51297751/229357106-3df7aac7-61e1-42b5-8320-03f703927d6f.png)

**Comment by Gaffers2277** [comment]
@1hitsong Hi, any update on what might be my problem?

**Comment by 1hitsong** [comment]
Not yet. I likely won't have time to re investigate until this weekend.

**Comment by 1hitsong** [comment]
@Gaffers2277 We just pushed 1.6.4 live and it has a new setting called Playback Bitrate Limits. If you disable this setting, does the problem video act any differently?

**Comment by Gaffers2277** [comment]
No it didn't, I think the issue is a bitrate issue, as only high bitrate h265 videos seem to crash, but that new setting being disabled didn't fix the crashing

**Comment by Gaffers2277** [comment]
@1hitsong I have solved the issue. After some researching i looked into what codecs my graphics card was compatiable to transcode and my Nvidia 960M in my Laptop cant transcode VP8/9 and HEVC 10bit. So once i turned off those codecs in the transcoding settings on the server side, the Roku started playing them again as direct play. Seems to be working now and i haven't run into any devices that cant direct play HEVC/H265.

**Comment by 1hitsong** [comment]
That's awesome you got it resolved! Thanks for following up and letting us know too!

**Comment by Gaffers2277** [comment]
@1hitsong Yeah hopefully if someone else has this issue it will help. Wasn't something i would have thought about until looking further into NVENC and realising it could be incompatability issues. Thanks for the help.

**Comment by Gaffers2277** [comment]
@1hitsong Well its back again, it just started crashing when i try to play videos. Its weird as it haven't touched a setting since and now it crashes when i play H265 and H264! So im back to being slightly stumped about what is causing the issue. It seems to affect stuff i watched before as well, for example i watched probably a full season of Stargate Atlantis but now it just crashes to the roku home page. It seems to be any bitrate and i tried limiting the bitrate to see if it was that but it seems to call the server but the server never gets a chance to send the video. I have a Intro preroll i play and it doesn't even get that far. It doesnt even show up in the logs on the server as direct play or transcode. If i remember correctly most of what i was watching was direct play except i transcode the audio to stereo from the Blu-ray 5.1. Is there anything that comes to mind that could cause this behaviour?? Like wrong settings or like maybe my FFMpeg is broken?? Im new to transcoding in general as i used to watch everything through VLC until i learnt about media servers.

**Comment by candry7731** [comment]
@Gaffers2277 Do you know how to sideload developer apps on the roku? if so you could try this zip file. 
[Jellyfin-Roku-dev-c20d5a149464e0a4a32b09b037a6a2476db77d9d (1).zip](https://github.com/jellyfin/jellyfin-roku/files/11943750/Jellyfin-Roku-dev-c20d5a149464e0a4a32b09b037a6a2476db77d9d.1.zip)


if you need help sideloading the zip file you can view this how to guide, https://github.com/jellyfin/jellyfin-roku#beta-test

Let me know once you have added the deveolper app and let me know if this fixes your errors.

**Comment by cewert** [comment]
@candry7731 FYI there are sideloading instructions on our readme: https://github.com/jellyfin/jellyfin-roku#beta-test

**Comment by candry7731** [comment]
> @candry7731 FYI there are sideloading instructions on our readme: https://github.com/jellyfin/jellyfin-roku#beta-test

Ah, I forgot those were updated! Thanks!

**Comment by OSS-GR** [comment]
I had a similar issue, it sort of did it with all types of content. I reinstalled the Roku app and it’s been working great since.

**Comment by cewert** [comment]
Hi @Gaffers2277 

Are you still experiencing this issue on the latest v1.6.6 release?

If so, can you tell me your device model? Also, can you _disable_ the following user settings and see if that helps?


- These are in Settings -> Playback -> Codec Support:
	- playback.mpeg4
	- playback.mpeg2
	- playback.av1
- These are in Settings -> Playback -> Profile Level Support:
	- playback.tryDirect.h264ProfileLevel
	- playback.tryDirect.hvecProfileLevel

**Comment by cewert** [comment]
If you are still experiencing this issue with version `2.1.8` or later then please reopen or make a new issue.
