### ISSUE TITLE
AudioLanguagePreference not respected

### ISSUE THREAD

**Issue by fice-t** [jellyfin-archive/jellyfin-roku-legacy#1341]
## Software Versions

- Jellyfin Server Version:  10.8.10
- Roku Client Version:  1.6.6

## Describe the bug
"Preferred audio language" is set to English, yet on Roku it still plays audio track 1 by default (unless changed with `*` beforehand). The web UI handles it correctly for the same files.

## How To Reproduce

1. In the web UI set  "Preferred audio language" to English.
2. Add a `.mkv` video with a non-English audio track 1 and English track > 1.
3. Play the video.
4. Non-English audio track is being used.

## Expected behavior
English audio track is being used if present.

## Additional context
The relevant server setting is `AudioLanguagePreference` which `jellyfin-roku` on the surface [appears to take into account](https://github.com/jellyfin/jellyfin-roku/blob/28f1ca5ff759a615a0b6244b9dd86f3423098557/components/ItemGrid/LoadVideoContentTask.brs#L388). Are there any logs that I could check to find out more? Or perhaps some debug output could be added?

**Comment by cewert** [comment]
>The relevant server setting is AudioLanguagePreference which jellyfin-roku on the surface [appears to take into account](https://github.com/jellyfin/jellyfin-roku/blob/28f1ca5ff759a615a0b6244b9dd86f3423098557/components/ItemGrid/LoadVideoContentTask.brs#L388). Are there any logs that I could check to find out more? Or perhaps some debug output could be added?

I don't know of any logs or debugging output that could help you but I just want to point out that the code you linked will always play the first audio track when the `PlayDefaultAudioTrack` user setting is set to `true`. In other words, `AudioLanguagePreference` will be ignored by design if `PlayDefaultAudioTrack` is set to true.

**Comment by fice-t** [comment]
Right, I forgot to mention that `PlayDefaultAudioTrack` was also unchecked through the web UI. I also made sure to restart the server and re-install the client.

**Comment by jimdogx** [comment]
This was fixed a while ago... we just haven't released a new build yet...

https://github.com/jellyfin/jellyfin-roku/pull/1265

**Comment by stephenshutters** [comment]
There have been a few new builds since then, yet I am still experiencing this problem ([as documented here](https://github.com/jellyfin/jellyfin-roku/issues/1277)).

**Comment by kkyucon** [comment]
Same issue here.

**Comment by zu-gabe** [comment]
The issue seems still to persist on the latest version

**Comment by stephenshutters** [comment]
I’ve noticed that this issue only occurs (and always occurs) when the audio file is of a DTS-HD MA format. It seems that Roku can’t handle it, which is frustrating as h*eck, since half of my movies are remuxes with DTS-HD MA audio tracks.
