### ISSUE TITLE
Selecting subtitles causes stream to crash

### ISSUE THREAD

**Issue by RBR8man** [jellyfin-archive/jellyfin-roku-legacy#1570]
## Software Versions

- Jellyfin Server Version:  
10.8.13
- Roku Client Version:  
2.0.0
## Describe the bug
Select a subtitle and player pops up an error saying error during playback, screen goes black but audio still plays

## How To Reproduce
1. start a video 
2. select a subtitle from dropdown and hit ok
3. problem

## Expected behavior
subtitle should be displayed normally

## Logs
https://[pastebin.com/raw/PRFPnz9h](https://pastebin.com/raw/PRFPnz9h)
Note: under advanced, logs, this is the latest one I have, not certain if this is after I downgraded or not

## Connection Information
locally played on a Roku streaming stick and on a Roku TCL tv

## Additional context
downgraded to 1.6.6 and problem no longer occurs

**Comment by cewert** [comment]
Hello and thanks for the bug report.

Your ffmpeg log shows that you have subtitles in a few different languages. Looks like English, Korean, Japanese, and Chinese.

Which language are you selecting to cause the crash? Does it crash for all of them? Do you have custom subtitles enabled?

**Comment by Mr-Generic123** [comment]
I'm seeing the same issue with only one subtitle embedded in the video:  English.
If they are embedded in the video (like from a DVD rip), it causes a crash.
If they are an external .SRT file, I don't see the crash.

This crash did not happen in the previous version of the Jellyfin client for Roku.

**Comment by cewert** [comment]
Thanks for the report @Mr-Generic123 

FYI for anyone experiencing this issue: We can't update the app till January 2nd due to the [roku holiday blackout](https://blog.roku.com/developer/channel-store-blackouts-2023). Best case scenario we fix it before then, push an update on the 2nd, and then the app hits rokus a few days later. Worst case it takes us a few weeks/months to figure out the bug. Unfortunately, the only workaround until then is to downgrade or sideload v1.6.6.

**Comment by 1hitsong** [comment]
@Mr-Generic123 @RBR8man Do you have the custom subtitles setting enabled?

**Comment by denetii** [comment]
I can confirm the same thing is happening to me, also with a TCL Roku TV. It looks like this occurs any time the server needs to transcode the video because the subtitle format is not natively supported. It can be sort of worked around by waiting at the 'Error During Playback' message/menu until you hear the audio playing, then pressing back (selecting OK will soft lock the app at a black screen and require a restart). If done successfully, the transcoded media with subtitles plays as it should.

This probably isn't terribly useful, but I had pulled a dev build at the start of the month (commit #e88356a). I went back and checked and the issue is present in that build as well, so I can at least say it's older than that.

**Comment by weirdofhermiston** [comment]
Let me know if this is a different issue, but when I select an external SRT file in the Roku app during a show, it takes a long time to load and then jumps back to the beginning of the episode. This wasn't a problem until 2.0.

**Comment by 1hitsong** [comment]
If you can, please test and see if my code changes in this PR fixes this bug.

https://github.com/jellyfin/jellyfin-roku/pull/1608

**Comment by photonconvergence** [comment]
Fixes the bug for me (tested with embedded SubRip subtitles).

**Comment by 1hitsong** [comment]
In that case, bug should be fixed in upcoming 2.0.1 release.

**Comment by mikeSGman** [comment]
I'm having the same issue; every track in my library (mix of h.265 1080p and 4k videos) only has one audio track, and one subtitle track, and playing on a Samsung tv causes it to crash. Ubuntu 22.04 server, Intel(R) Xeon(R) CPU D-1528 6 core (12 threads) and 128G of ddr3 ram with nvme boot volume, and SSD data volume. By the time ffmpeg starts to transcode the subtitles, the system is dead within a few seconds.

**Comment by EzequielBruni** [comment]
Has this been fixed for anyone? Because it's still an issue on my Roku TV.
