### ISSUE TITLE
Roku Jellyfin 2.0.1 unable to remember different profiles

### ISSUE THREAD

**Issue by sanqdinh** [jellyfin-archive/jellyfin-roku-legacy#1636]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.1

## Describe the bug

After updating from 2.0.0 Jellyfin Roku client to 2.0.1, the client does not save the passwords of different user profiles on the same server. 

## How To Reproduce

1. Create two user accounts "A" and "B"
2. Login to "A" on Jellyfin Roku. ("Save Credentials" is selected)
3. Press "*" on the remote, "Change User"
4. Login to "B" ("Save Credentials" is selected)
5. Press "*" on the remote, "Change User", and reselect "A"
6. The 2.0.1 Roku Client now requires to type in the password for "A" again. This does not happen in 2.0.0 (The client will automatically login to "A" again.)

## Logs
The following are the Logs from the SERVER

[2024-01-12 15:30:58.084 +00:00] [INF] [3] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "User A" has succeeded.
[2024-01-12 15:30:58.084 +00:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "User A": 2/0
[2024-01-12 15:30:58.086 +00:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user e3c01808-2602-48c5-875a-b1490b5f6e8d
[2024-01-12 15:31:26.885 +00:00] [INF] [51] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-01-12 15:31:26.885 +00:00] [INF] [51] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-01-12 15:31:26.887 +00:00] [INF] [51] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
[2024-01-12 15:31:26.924 +00:00] [INF] [29] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2024-01-12 15:31:27.064 +00:00] [ERR] [29] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2024-01-12 15:31:27.077 +00:00] [INF] [29] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "User B" has been denied (IP: "192.168.0.7").
[2024-01-12 15:31:27.079 +00:00] [ERR] [29] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/AuthenticateByName".

## Connection Information

- Is server local or remote: Local
- Is server connection HTTP or HTTPS: HTTP

**Comment by cewert** [comment]
Thank you for reporting this. I'm looking into it.

**Comment by cewert** [comment]
I'm able to reproduce using 2.0.0 and 2.0.1 (the users must have passwords and you must switch between two users to reproduce). 

I think this was broken in #1441 because I'm not seeing the username get appended to the end of the auth header in my testing and I know this was working at some point.

**Comment by cewert** [comment]
Bug was caused by [these lines](https://github.com/jellyfin/jellyfin-roku/blob/3b888d40a0e8bc774a32660917129e7e2955a518/source/utils/session.bs#L195-L199) not actually updating the global device array. Fixed in #1640

**Comment by Docano** [comment]
This issue still persists. Reproduced this issue today on Jellyfin Roku 2.0.7 and Jellyfin 10.8.13.

**Comment by cewert** [comment]
@Docano please open a new issue and provide as much detail as possible.
