### ISSUE TITLE
1.3.5 transcodes by default

### ISSUE THREAD

**Issue by jcdick1** [jellyfin-archive/jellyfin-roku-legacy#261]
**Describe the bug**
1.3.5 client transcodes supported video codecs by default.  Transcoding must be turned off on the user profile to force direct play.

**To Reproduce**

1. Open Roku 1.3.5 client on Roku Premiere/Ultra
2. Select video encoded in, for this example, HEVC
3. Playback shows "Transcoding" on the dashboard, and heavy CPU usage
4. Stop playback
5. In the JF server "Users" dashboard, unselect "Allow video playback that requires transcoding," "Allow audio playback that requires transcoding" and "Allow video playback that requires conversion without re-encoding."
6. Return to HEVC video
7. Playback resumes, with *much* less CPU usage. Though for some reason, the JF server is still reporting "Transcoding" in the User client connection panel on the dashboard, but that's one for the JF server team.

**Expected behavior**
The client should default to direct play/stream for detected codec support

**Logs**

**Screenshots**
![roku_bug_1](https://user-images.githubusercontent.com/49927327/88747814-2b591c00-d115-11ea-920d-fc6e141ecbdc.png)
![roku_bug_2](https://user-images.githubusercontent.com/49927327/88747816-2e540c80-d115-11ea-99d1-03192b6a568e.png)
![roku_bug_3](https://user-images.githubusercontent.com/49927327/88747824-314efd00-d115-11ea-9a64-1cbec467c8e4.png)
![roku_bug_4](https://user-images.githubusercontent.com/49927327/88747985-9276d080-d115-11ea-90f9-fcb15643e109.png)
![roku_bug_5](https://user-images.githubusercontent.com/49927327/88747988-94d92a80-d115-11ea-9602-dd331f3c0803.png)

**Additional context**
I'm guessing the client isn't reporting capabilities back to the server quite the way one would expect, as it transcodes by default, but turning off all transcoding capability still allows playback.

**Comment by neilsb** [comment]
Since this has a AC3 audio track, I'm assuming you're connected to an external decoder?  My guess would be that the Roku isn't reporting that the decoder supports AC3, but when you're forcing direct play it's just passing it through and the decoder is handling it.

Could you check the _Settings_ -> _Audio_ -> _HDMI_ menu in your Roku and see what it's it's set to?  Default is _Auto detect_ and if it's set to that can you see what it shows as "Detected"?

As a test, if you could set it manually to _Dolby Digital_ (or a higher one if your decoder supports it) and try it again and see if that stops transcoding?

Also, can I just check this is v1.3.5 from the Store and not the Beta app (There's a bug in the 1.3.5 beta that causes issues when detecting supported audio)?

**Comment by neilsb** [comment]
Just spotted on your reddit comment that you tried the beta.   The first thing to try is the store version and see if that solves it.

As mentioned in the comment above, there is a bug in the 1.3.5 beta release that was fixed as part of the work that was needed to get it through approval for live.  So unfortunatly the live and beta 1.3.5 are marginally different.  We'll get the version on the beta cleaned up soon.

**Comment by jcdick1** [comment]
It is still the same on the 1.3 (Build 5) Store version:

This is with the same file.

With all transcoding enabled in the server user config

![roku_bug_7](https://user-images.githubusercontent.com/49927327/88817528-3c407680-d183-11ea-99e9-b978bb565ef2.png)

Playback nearly pegs all 8 CPUs:

![roku_bug_6](https://user-images.githubusercontent.com/49927327/88817540-3ea2d080-d183-11ea-9ebd-b1da64341978.png)

If I turn off Video transcoding only, leaving audio transcoding enabled:

![roku_bug_9](https://user-images.githubusercontent.com/49927327/88817593-52e6cd80-d183-11ea-8d10-c0cbc8d10579.png)

The CPU usage is not using all 8 CPUs concurrently, transcoding just the audio stream:

![roku_bug_8](https://user-images.githubusercontent.com/49927327/88817637-64c87080-d183-11ea-9e25-4489cdf6fb73.png)

If I disable all transcoding:

![roku_bug_10](https://user-images.githubusercontent.com/49927327/88817734-7f024e80-d183-11ea-8b6d-5bd9af4fcd36.png)

CPU usage is nearly non-existent:

![roku_bug_11](https://user-images.githubusercontent.com/49927327/88817793-8e819780-d183-11ea-93a2-78d88a4c6482.png)

The client is definitely defaulting to transcoding for all streams.  To what, I am not sure.

**Comment by neilsb** [comment]
In lieu of more information on the roku client (or the server dashboard :) you should be able to get that information from the server logs.   The ffmpeg call should be logged in the default INFO logging level

e.g.
`[16:04:35] [INF] [5] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg .....`

**Comment by jcdick1** [comment]
Kicking off another playback, here's a section of the logs:

```
[2020-07-29 16:52:51.667 +00:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 192000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp4,m4v,mov", AudioCodec: "mp3,pcm,lpcm,wav,alac,aac", VideoCodec: "h264,h265", Type: Video }, DirectPlayProfile { Container: "mkv,webm", AudioCodec: "mp3,pcm,lpcm,wav,flac,alac,aac,opus,vorbis", VideoCodec: "h264,vp8,h265,vp9", Type: Video }, DirectPlayProfile { Container: "mp3,pcm,lpcm,wav,wma,flac,alac,aac,wmapro", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: External, DidlMode: null, Language: null, Container: null }] }
[2020-07-29 16:52:51.695 +00:00] [INF] User policy for "Test". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-07-29 16:52:51.696 +00:00] [INF] Profile: "Unknown Profile", Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-07-29 16:52:51.696 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv"
[2020-07-29 16:52:51.696 +00:00] [INF] Profile: "Unknown Profile", Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-07-29 16:52:51.696 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv"
[2020-07-29 16:52:51.696 +00:00] [INF] Profile: "Unknown Profile", Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2020-07-29 16:52:51.697 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/media/video/movies/the_african_queen_(1951).mkv"
[2020-07-29 16:52:52.628 +00:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2020-07-29 16:52:52.629 +00:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska,webm -i file:"/mnt/media/video/movies/the_african_queen_(1951).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -profile:v high -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 aac -ac 2  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/e3614291a68640f6d52bffc9e4e0aa33%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/e3614291a68640f6d52bffc9e4e0aa33.m3u8"
[2020-07-29 16:52:54.446 +00:00] [WRN] HTTP Response 200 to "192.168.0.194". Time (slow): 0:00:01.845668. "http://jellyfin.host.net:8096/Videos/6515500866eaf159d4616941aed0dcd9/hls1/main/0.ts?AudioCodec=aac&BreakOnNonKeyFrames=True&h264-profile=high%2Cmain%2Cbaseline%2Cconstrainedbaseline&MaxAudioChannels=2&MediaSourceId=6515500866eaf159d4616941aed0dcd9&MinSegments=1&PlaySessionId=1196317f82b74c6a84fb072e6e10f408&RequireAvc=false&SegmentContainer=ts&VideoCodec=h264"
```

So I'm guessing the profile coming back from the Roku client isn't being recognized by the server, as it keeps referring to an "Unknown Profile." Also, the full run of capabilities is coming back, as opposed to simply "yes, I can play that." So it kicks off an ffmpeg session, and it looks like it's converting to h264/AAC.

**Comment by anthonylavado** [comment]
@jcdick1 There's still an important item to check. From @neilsb earlier:
> Could you check the Settings -> Audio -> HDMI menu in your Roku and see what it's it's set to? Default is Auto detect and if it's set to that can you see what it shows as "Detected"?
>
>As a test, if you could set it manually to Dolby Digital (or a higher one if your decoder supports it) and try it again and see if that stops transcoding?

**Comment by jcdick1** [comment]
Okay, it was detecting HDMI audio as "Stereo" on the Roku, so I forced it to Dolby Digital Plus.  That appears to have squashed it.  So it would seem there's an audio detect bug in the Store version, as well.

It's interesting, but unrelated, that the RAM usage on the server dropped _after_ playback started too.  I'd think it would go up from idle.

![roku_bug_12](https://user-images.githubusercontent.com/49927327/88833508-f8a43780-d197-11ea-928c-e927fa3b370f.png)

**Comment by neilsb** [comment]
OK, thanks.  So it's not audio detection problem with the Jellyfin app as such, but rather the Roku detection of you decoder audio properties.   If the Roku thinks that the decoder only handles Stereo, then since the Audio Track is DD then as far as Roku is concerned, there is nothing that can handle that, so it needs to transcode.

However, from the logs (and my testing here) it looks like it is also transcoding the video, when it _should_ only be transcoding the Audio (and Remuxing).  I'm not sure if this a problem at the Roku end, or a server issue, so I'll have a further look into that.

**Comment by jcdick1** [comment]
>If the Roku thinks that the decoder only handles Stereo, then since the Audio Track is DD then as far as Roku is concerned, there is nothing that can handle that, so it needs to transcode.
> 
But if the Roku is genuinely reporting it can't play the audio because it is connected to a "Stereo" device via HDMI and so doesn't know what to do with it and so requires transcoding, wouldn't turning off allowing transcoding on the server cause the file to not be played, or the audio to be silent, instead of doing its own conversion on-board the device?  What allows the Roku to accept the forced direct play but not the "dynamically created profile" direct play?

**Comment by anthonylavado** [comment]
So the detection is what your _output_ device supports, but not what the Roku can play. I'm not sure where you're located, but here's the lowdown:

Dolby Digital is part of the ATSC broadcasting standard (and many others). As such, many TVs will by default have AC-3 decoding at a minimum. Not all sets will pass through Dolby Digital or other formats though, so things get more complex there.

So there's two possiblities:

1) The output device is not reporting it's own capabilities correctly. It is falling back to two-channel Stereo, and not advertising the fact that it can decode Dolby Digital (this could happen with an HDMI switch or something else along the line as well)

2) The Roku itself (not the app) is not interpreting your output device's capabilities correctly

At any rate most HDTV sets since ~2007 (at least in North America anyway) will have an ATSC tuner, and thus Dolby Digital decoding capabilities built in. So that's why the file still plays even when your turn off the transcoding. At that point, all the Roku can do is pass along the audio its receiving, and let the output device do what it will.

I have tested this to be true as well - I have two sample files. One with DTS audio, and another with Dolby Digital Plus. I connected the Roku to my older TV from ~2009, which has an ATSC tuner (and thus Dolby decoding), but not DTS support. The (new) Roku Streaming Stick+ reported only Stereo capabilities, as yours did. Trying to play either sample file resulted in transcoding. If I manually enabled all capabilities (Dolby Digital Plus, and DTS), the Dolby sample played back (DD+ gracefully falls back to DD), but the DTS file played silently.

**Comment by neilsb** [comment]
And I've found the reason why the video was being transcoded instead too of just the audio.  (related to #45).

If we need to transcode Audio or Video, then we end up specify that the video format we want is h264.  If we support it, we should be leaving it as the source codec.   Should be easy enough to sort.

**Comment by jcdick1** [comment]
Gotcha.  I was under the impression that when the Roku advertises its capabilities, it was then doing the work of things like downmixing from 5.1 to stereo or conversion from one codec to one supported by the output device.  That if I hooked it up to a TV that only supported PCM stereo, for instance, that the Roku would still tell the server it can direct play AC3, but then do the conversion to PCM itself, like it does with video.

Edit:  I hate to be _that guy_, but I thought I'd double-check the Plex client, and with the HDMI audio on autodetect ("Stereo") it direct plays everything I've got.  I wonder what their server or client code is doing differently.

**Comment by anthonylavado** [comment]
Roku's Docs actually have some interesting info (thanks to @neilsb for the link): https://developer.roku.com/docs/specs/streaming.md (scroll to Supported Audio Codecs)

Of note:
> Roku TVs and Roku Ultra can decode AC3 and E-AC3. All other Roku devices will do passthrough to the receiving device. Roku Ultra supports the latest Dolby technologies such as Dolby Atmos and System Sound Mixing (MS12).

Regarding your question @jcdick1, it's possible that Plex has just assumed that everyone will be able to decode DD Stereo at this point, so they just send it along and don't bother transcoding it. In the age of most Roku devices having an HDMI connection, it's a reasonably safe bet.

Meanwhile, this channel was built from the ground up to try and detect capabilities fully, and not making any assumptions about what's supported (other than a baseline of H264 video).

**Comment by jcdick1** [comment]
Or, perhaps they don't use profiles the same way JF does, and simply gets the file metadata (.mkv, h265, ac3 5.1), polls the hardware for supported codecs on the device, and just sends back a "direct play container =yes, direct play video = yes, direct play audio = yes"

**Comment by jcdick1** [comment]
I'm not a coder, so I have to make guesses as to how various things work, but is it possible they are using GetAudioDecodeInfo() to fully list out all of the device supported codecs, thereby allowing direct play without having to necessarily change the Roku device audio settings?

As it shows in the example:

```
di = CreateObject("roDeviceInfo")
audioDecoders = di.GetAudioDecodeInfo()

REM Check for surround sound codecs:
hasDolbyDigital = audioDecoders.doesexist("AC3")
hasDTS = audioDecoders.doesexist("DTS")
hasDDPlus = audioDecoders.doesexist("DD+")
```

It seems to me, that covers all the audio settings on mine that can subsequently allow for direct play in the client, even 5.1 despite it being a two-speaker TV audio output.  Perhaps the Roku defaults to the "lowest common denominator" output when on "autodetect," thereby just going with "stereo".

**Comment by anthonylavado** [comment]
@jcdick1 We had to take that out as the Static Analyzer complained that it was deprecated. See https://github.com/jellyfin/jellyfin-roku/issues/259 and https://github.com/jellyfin/jellyfin-roku/pull/260.

...Well, we didn't *have* to take it out, but they were warning us that it will be removed.

**Comment by neilsb** [comment]
The `GetAudioDecodeInfo()` just gave a list of all the codecs that the Roku supported.   The _newer_ way of calling `CanDecodeAudio()` and passing it the code is built from the same data, but you just ask is specifically if it can decode something rather than getting a list of everything that it can handle.

So [here, in the code](https://github.com/jellyfin/jellyfin-roku/blob/master/source/VideoPlayer.brs#L230-L233) we take the codec used and check if the Roku supports it.

The problem is arising because if the HDMI is detecting that only Stereo is supported, a call to `CanDecodeAudio` of *dts* returns false.   This is the same result as a call to `GetAudioDecodeInfo()`, as *DTS* is only included in the list if the HDMI autodetects that DTS is supported, or it is manually overridden in the Roku settings.

We could add a Jellyfin setting to the Roku Client to allow to specify what codecs should be passed through, and this would then override what the Roku is reporting, or set to.  But that's just moving the manual config from the Roku to Jellyfin client.

**Comment by neilsb** [comment]
PR #269 should solve the problem with the Video being transcoded when only the audio is required.  

The ability for choosing Codecs that can be played directly even when Roku suggests it cannot can be addresses as part of #231.

**Comment by jcdick1** [comment]
Excellent!  Thank you very much for your work!
